### PR TITLE
Rspec setup

### PR DESCRIPTION
**Pull request by aleciabenjamin**
- set up rspec
- add gems
- add shoulda-matchers
- edit .rspec

### CODE REVIEW

**Review by Joberg95 — APPROVED** [review]
Great.

**Comment by perhegg** [comment]
fantastic!

**Review by perhegg — APPROVED** [review]
very good

**Review by LauraRe — APPROVED** [review]
looks good to me!

**Comment by faraznaeem** [comment]
Description is missing and needs a better title

**Review by faraznaeem — CHANGES_REQUESTED** [review]
The configuration for the shoulda mathchers is missing please go over the course documentation for more details is the latest code pushed up?

**Review by perhegg — APPROVED** [review]
gooood

**Review by LauraRe — APPROVED** [review]
Good!

**Review by tochman — COMMENTED** [review]
You should add one test framework per PR

**Pull request merged**
